# Site settings
title: Docassemble
email: jhpyle@gmail.com
description: > 
  A python module for assembling documents from templates while 
  automatically querying a user for necessary information.
baseurl: ""
url: "http://docs.docassemble.org" # the base hostname & protocol for your site
github_username:  jhpyle
collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: "docs"
      type: docs
    values:
      layout: docs

# Build settings
markdown: kramdown
