# Site settings
title: "Docassemble"
email: "jhpyle@gmail.com"
description: >
  A free, open-source expert system for guided interviews and document assembly, based on Python, YAML, and Markdown.
baseurl: ""
url: "http://docassemble.org"
demourl: "https://demo.docassemble.org"
github_username: jhpyle
collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: "docs"
      type: docs
    values:
      layout: docs

# Build settings
markdown: kramdown
